// Regenerates src/confusables-table.ts from Unicode's confusables.txt (UTS #39).
// Usage: bun packages/shared/scripts/gen-confusables.ts [path/to/confusables.txt]
// Without a path it downloads the pinned version. The table is data under the Unicode
// licence (https://www.unicode.org/license.txt), which is compatible with AGPL-3.0.
// To move to a new Unicode version, change VERSION and SHA256 together (ADR 0022).

const VERSION = "18.0.0";
const SOURCE = `https://www.unicode.org/Public/${VERSION}/security/confusables.txt`;
const SHA256 = "6ed3ee967c9dfdf6677d563c9985182fbc50a2efb7d6059cd57b2e2ce18f5b92";
const OUT = `${import.meta.dir}/../src/confusables-table.ts`;

/** Code points a nickname can hold after NFKC, NFD and lowercasing (NicknameSchema). */
const NICKNAME_CHAR = /^[\p{L}\p{N}\p{M}_.\- ]$/u;

async function load(path: string | undefined): Promise<string> {
  if (path !== undefined) return Bun.file(path).text();
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`${SOURCE}: HTTP ${String(res.status)}`);
  return res.text();
}

const text = await load(process.argv[2]);
const hash = new Bun.CryptoHasher("sha256").update(text).digest("hex");
if (hash !== SHA256) throw new Error(`confusables.txt sha256 ${hash}, expected ${SHA256} (version ${VERSION})`);

const fromHex = (field: string): string =>
  String.fromCodePoint(...field.trim().split(/\s+/).map((h) => Number.parseInt(h, 16)));

let entries = "";
let count = 0;
for (const line of text.split("\n")) {
  const data = line.replace(/#.*/, "").trim();
  if (data === "") continue;
  const [source, target] = data.split(";");
  if (source === undefined || target === undefined) throw new Error(`bad line: ${line}`);
  const from = fromHex(source);
  // Characters a nickname can never contain are never looked up: leave them out.
  if (!NICKNAME_CHAR.test(from)) continue;
  entries += `${from}${fromHex(target)}\n`;
  count++;
}

// Escape everything outside printable ASCII so the file has no invisible characters.
let literal = "";
for (const c of entries) {
  const cp = c.codePointAt(0) ?? 0;
  if (c === "\n") literal += "\\n";
  else if (c === "\\" || c === '"') literal += `\\${c}`;
  else literal += cp >= 0x20 && cp < 0x7f ? c : `\\u{${cp.toString(16)}}`;
}

await Bun.write(
  OUT,
  `// Generated by packages/shared/scripts/gen-confusables.ts — do not edit.
// Source: ${SOURCE}
// sha256 ${SHA256}
// © Unicode, Inc. Unicode licence: https://www.unicode.org/license.txt
// ${String(count)} entries; each is one source code point, then its prototype, then "\\n".
// Server-only: import through "@omega/shared/confusables", never from the main entry.
export const CONFUSABLES_VERSION = "${VERSION}";
export const CONFUSABLES = "${literal}";
`,
);
console.log(`wrote ${String(count)} entries to ${OUT}`);
